### ISSUE TITLE
완제품 주문 기능 구현

### ISSUE THREAD

**Issue by susooo** [PreScent-sc23/backend#13]
📝**기능 설명**
- 장바구니에 담겨있는 완제품들을 주문하는 기능
- 결제가 완료되면 주문이 만들어진다. 
- 주문에는 주문한 고객, 주문을 받은 판매자, 주문 일시, 픽업 일시 등의 주문정보가 들어간다. 

‼️**배경**
- 고객이 장바구니에 담은 완제품을 주문하기 위해 필요

✅**추가 정보**
- 주문 데이터베이스의 정보를 통해 고객의 주문기록 조회, 판매자의 주문 기록 조회를 할 수 있다.

**Comment by Ajou-sipdo** [comment]
완료
