### ISSUE TITLE
고객 장바구니 확인 기능 구현

### ISSUE THREAD

**Issue by susooo** [PreScent-sc23/backend#18]
📝**기능 설명**
- 구현한 기능에 대해 설명해주세요.

‼️**배경**
- 이 기능이 왜 필요한지, 어떤 문제를 해결하기 위한 것인지 설명해주세요.

✅**추가 정보**
- 기타 관련된 정보나 참고사항을 추가해주세요.

**Comment by Ajou-sipdo** [comment]
완료
