### ISSUE TITLE
매장 등록, 완제품 등록 기능 구현

### ISSUE THREAD

**Issue by susooo** [PreScent-sc23/backend#19]
📝**기능 설명**
- 판매자가 매장 이름, 번호, 위치, 운영시간 등 매장 정보를 등록하는 기능
- 판매자가 등록한 매장에서 판매할 완제품을 등록하는 기능
- 완제품 이름, 완제품 사진, 가격, 설명, 포함된 꽃 등 완제품 정보를 적어 등록 요청을 하면 백엔드는 사진을 아마존 S3서버에 저장하고 url를 받아 다른 정보들과 함께 DB에 저장한다.

‼️**배경**
- 판매자가 매장을 등록하고 완제품을 등록하기 위해 필요

**Comment by Ajou-sipdo** [comment]
주문db에 집어넣는것까지 성공

**Comment by Ajou-sipdo** [comment]
매장 등록 프론트엔드와 연동 완료
완제품 등록 프론트엔드와 연동하려 했으나 프론트에서 업로드한 이미지 처리 못함
프론트에서 업로드한 이미지 처리하고 아마존 S3 구축하여 
아마존 S3 구축하여 S3에 이미지 넣고 fileURL받아오기 성공
프론트엔드 연동 성공
