### ISSUE TITLE
판매자 회원가입 기능 구현

### ISSUE THREAD

**Issue by susooo** [PreScent-sc23/backend#6]
📝**기능 설명**
- 판매자가 사업자번호, 판매자이름, 로그인 시 ID로 사용할 이메일, 비밀번호, 전화번호를 입력하여 DB에 판매자 회원가입을 진행한다.

‼️**배경**
- 구매 고객과는 다르게 사업자 번호가 있어야만 판매자로 회원가입할 수 있어야 하기 때문에 고객과 구분되어 회원가입을 진행하도록 기능을 구현한다.

✅**추가 정보**
- spring security로 비밀번호 암호화

**Comment by headcha** [comment]
@susooo 완료된거면 close 시켜주세요

**Comment by susooo** [comment]
@headcha 네, 확인 감사합니다
